export const BAT_SWING_OFFSET_DURATION = 400;
export const BAT_SWING_OFFSET_DELAY = 300;
export const BAT_HIT_DURATION = 100;
export const BAT_HIT_DELAY = 200;

export const BAT_HIT_ANIMATION_TOTAL =
  BAT_SWING_OFFSET_DURATION + BAT_SWING_OFFSET_DELAY + BAT_HIT_DURATION + BAT_HIT_DELAY;
